### ISSUE TITLE
hash login password 

### ISSUE THREAD

**Issue by amjed-98** [GSG-G11/What-toDo-today#17]
#4 
## Tasks

- [x] implement hash password function
- [x] implement compare password function
- [x] compare hashed password with db password
