### ISSUE TITLE
edit todo

### ISSUE THREAD

**Issue by amjed-98** [GSG-G11/What-toDo-today#30]
#29 
- [ ] add test PATCH /todo route
- [ ] add PATCH /todo route 
- [ ] add db query to edit note
