### ISSUE TITLE
delete todo

### ISSUE THREAD

**Issue by amjed-98** [GSG-G11/What-toDo-today#31]
#29 
- [x] add test DELETE /todo route
- [x] add DELETE /todo route 
- [x] add db query to delele note
